"""empty message

Revision ID: 3d0df3094eb4
Revises: 8453c3f02fea
Create Date: 2020-05-31 01:30:34.501942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d0df3094eb4'
down_revision = '8453c3f02fea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todolist', sa.Column('completed', sa.Boolean(), nullable=True))

    op.execute('UPDATE TodoList SET completed = False WHERE completed IS NULL;')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todolist', 'completed')
    # ### end Alembic commands ###
